### ISSUE TITLE
Failed to start

### ISSUE THREAD

**Issue by HumanTree92** [Xovos/esx_moneywash#1]
If you are getting failed to start in the __resource.lua file it needs to look like this
version '0.0.1'

server_scripts {
	
  '@es_extended/locale.lua',
	'locales/en.lua',
	'config.lua',
	'server/esx_wash_sv.lua'
}

client_scripts {
	'@es_extended/locale.lua',
	'locales/en.lua',
	'config.lua',
	'client/esx_wash_cl.lua'
}

ui_page 'html/ui.html'

files {
    'html/ui.html',
    'html/pdown.ttf',
    'html/img/cursor.png',
    'html/css/app.css',
    'html/scripts/app.js'
}

This is me taking out the local files that where removed by this user.

**Comment by HumanTree92** [comment]
Also to know if you have this problem is check your logs. If you have 
Failed to load script locales/de.lua.
Failed to load script locales/br.lua.
Failed to load script locales/fr.lua.
Failed to load script locales/es.lua.

then you need to make changes to your resource file

**Comment by Xovos** [comment]
I've Implemented it in the branch
thanks for the fix
